# 应用服务 WEB 访问端口
server:
  port: 8888

spring:
  profiles:
    active: dev

# 日志
logging:
  config: classpath:logback-weblog.xml

jwt:
  # 签发人
  issuer: slilio
  # 秘钥
  secret: jElxcSUj38+Bnh73T68lNs0DfBSit6U3whQlcGO2XwnI+Bo3g4xsiCIPg8PV/L0fQMis08iupNwhe2PzYLB9Xg==
