# 应用服务 WEB 访问端口
server:
  port: 8888

spring:
  profiles:
    active: dev

# 日志
logging:
  config: classpath:logback-weblog.xml

jwt:
  # 签发人
  issuer: slilio
  # 秘钥
  secret: 9pmKfM0gD+8KuWMJEovmW6F1KeH4eBFMXA/fCCIWon55uC19yl4oFYdk1RAOCNql8ksHyV5lIQfnZ/Gtkd8agg==
