# 应用服务 WEB 访问端口
server:
  port: 8888

spring:
  profiles:
    active: dev

# 日志
logging:
  config: classpath:logback-weblog.xml

jwt:
  # 签发人
  issuer: slilio
  # 秘钥
  secret: 9pmKfM0gD+8KuWMJEovmW6F1KeH4eBFMXA/fCCIWon55uC19yl4oFYdk1RAOCNql8ksHyV5lIQfnZ/Gtkd8agg==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer
