# 应用服务 WEB 访问端口
server:
  port: 8888

spring:
  profiles:
    active: dev
  mail:
    host: smtp.qq.com # 邮件服务器的地址，小哈这里使用的 QQ 邮件
    username: 1764759472@qq.com # 发送邮件的邮箱账号
    password: ezjewyjiebzgdied # 授权码，或发送邮件的邮箱账号的密码
    default-encoding: utf-8 # 邮件内容的字符编码
    protocol: smtps # 邮件传输协议：smtps 表示SMTP over SSL，是一种加密的SMTP连接方式，用于确保邮件传输的安全性。
    port: 465 # 邮件服务器的端口号：465 是 SMTPS（SMTP over SSL）的常用端口号，用于加密的邮件传输。


# 日志
logging:
  config: classpath:logback-weblog.xml

jwt:
  # 签发人
  issuer: slilio
  # 秘钥
  secret: 9pmKfM0gD+8KuWMJEovmW6F1KeH4eBFMXA/fCCIWon55uC19yl4oFYdk1RAOCNql8ksHyV5lIQfnZ/Gtkd8agg==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 144000
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer

#QQ信息获取api接口
qqinfoapi:
  apiUrl: https://api.nsmao.net/api/qq/query
  apiKey: ALOb8Waza2pHH7doZYmBZvURF8

#=================================================================
# TencentOSS 对象存储
#=================================================================
tencentcos:
  region: ap-beijing
  SecretId: ###
  SecretKey: ###
  bucketName: ###
  uploadFolder: webLogImg/